### ISSUE TITLE
[ActionTemplate] ActionGenerator improvement

### ISSUE THREAD

**Issue by c9s** [c9s/ActionKit#15]
RecordAction 有內建一些邏輯直接對 Model 操作

現在是直接在 ActionKit\ActionGenerator 註冊好哪些 model 有哪些 actions

但現有的預設值就是單純的 record action 直接 record 操作

我們的需求是，看能不能讓自動產生的 action 可以 check current user，如果是某個 user rule 才可以執行這個 action

現在的 Action class 裡面有一個 currentUserCan method，他現在是直接呼叫 model 的 currentUserCan

要改的地方是:

1. 現在的 ActionGenerator 有 Template-based generator 還有 CodeGen-based generator

Template 的話就是吃一個 Template file (要預先寫好)，CodeGen 的話就是用 PHP 的 CodeGen, programmatically 的 generate 一個 php class 然後載入回來

2. ActionGenerator 裡面有 generate2 跟 generate method，generate2 應該就是 codegen based generator

3. 看有沒有辦法從外部跟 ActionGenerator 註冊這兩種 generator，這樣我們可以從外部選用

4. 然後我們提供一組 CRUD Record Action Template 是有 currentUserCan method override 的

**Comment by azole** [comment]
```
abstract class ActionTemplateBased
{
    // 負責設定 generator 需要的 class 設定
    protected abstract function createTemplate($targetClassName, array $arguments);
    // 負責建立class
    public abstract function generate();
}
```

**Comment by c9s** [comment]
```php
$generator->registerTemplate('adminRecordAction', new AdminRecordActionTemplate);
```
